### ISSUE TITLE
Bugs in CmdBuffer::BindTransformFeedbackBuffers()

### ISSUE THREAD

**Issue by brianpaul** [GPUOpen-Drivers/xgl#45] opened 2019-12-05 23:27 UTC
1. At vk_cmdbuffer.cpp:5382 I believe the memset() should go into the preceding conditional.

2. The Vulkan spec says that pSizes=NULL is a valid argument (to indicate whole buffer).  But if pSizes is NULL we'll segfault at line 5401.

3. I think the for loop at line 5392 is wrong.  It think it should be for (i = 0; i < bindingCount; i++).  Then, inside the loop, the m_pTransformFeedbackState->params.target[i] array should be indexed with firstBinding + i instead.  Also the 1 << i expression should then be 1 << (firstBinding + i).

**Comment by crystalJinamd** [comment] 2019-12-23 02:55
fixed internally

**Comment by jinjianrong** [comment] 2020-05-13 23:41
The issue is fixed in latest code

**Closed by jinjianrong** 2020-05-13 23:41 UTC
Labels: assigned
