### ISSUE TITLE
shaderdb test Ext16bitStorage_TestTesOutput.tese hits infinite loop

### ISSUE THREAD

**Issue by alan-baker** [GPUOpen-Drivers/xgl#31] opened 2018-07-05 19:09 UTC
When I run the shaderdb test Ext16bitStorage_TestTesOutput.tese, it hits an infinite loop in the DAG combiner during backend code generation.

**Comment by linqunzju** [comment] 2018-07-06 00:44
I suppose you run this test with gfxip = 9, it is a known issue, we will fix it ASAP.

**Comment by jinjianrong** [comment] 2018-07-20 02:50
@alan-baker The issue is fixed in latest LLVM, please try it.

**Closed by jinjianrong** 2018-07-20 02:50 UTC
Labels: assigned, fixed, fixed internally
