### ISSUE TITLE
DOOM and Wolfenstein II not working

### ISSUE THREAD

**Issue by libcg** [GPUOpen-Drivers/xgl#24] opened 2018-04-26 05:42 UTC
When running DOOM or Wolfenstein II under Wine, I'm getting a black screen and the game freezes there. I haven't been able to run those two games for at least a month now. It works fine using RADV.

Using Ryzen 1700X / R9 Fury.

**Comment by jinjianrong** [comment] 2018-04-26 06:01
Are you running the driver built from latest source code? We can run Wolfenstein II under Wine well, will check the issue with DOOM

**Comment by libcg** [comment] 2018-04-26 16:47
I'm using latest build from yesterday, wine-staging 3.6 and Linux 4.16.

**Comment by libcg** [comment] 2018-05-01 04:02
Same issue with xgl@67fcf19, wine-staging 3.7, libdrm 2.4.91, linux 4.16.5.

**Comment by libcg** [comment] 2018-05-12 19:09
Same issue with xgl 67fcf19. Note that AMDGPU-PRO 18.20 seems to work fine in the same setup using mainline libdrm and linux 4.16.8.

**Comment by libcg** [comment] 2018-05-12 19:10
Works fine with AMDGPU-PRO 18.20 Vulkan driver on top of mainline libdrm and linux 4.16.8

**Comment by libcg** [comment] 2018-05-15 04:14
Still hanging with ef2ad11

**Comment by crystalJinamd** [comment] 2018-05-15 06:09
Can latest DOOM run in vulkan mode with DOOMx64vk.exe ? On my desktop, DOOMx64.exe was started even when I directly ran with DOOMx64vk.exe.

**Comment by crystalJinamd** [comment] 2018-05-15 07:02
Did you run with debug amdvlk driver ? And what's the detail issue, is black screen showed in the first frame ?

I'm not sure mine is same as yours, since I updated DOOM to the latest version, radv, amdgpu-pro and amdvlk are all started in OGL mode that will get black screen at the first frame even I directly ran with DOOMx64vk.exe.

**Comment by libcg** [comment] 2018-06-02 16:46
Still broken with 46e77e3, I can confirm that `DOOMx64vk.exe` is running, and yes it's a black screen.

**Comment by jinjianrong** [comment] 2018-06-04 08:53
@libcg The Wolfenstein II issue should have been fixed with latest code, could you help confirm it? However with latest Doom, we are still seeing the issue with radv, amdgpu-pro and amdvlk, and it seems to be an OGL issue (Doom runs in OGL mode at the beginning), could you help double check it? Thanks

**Comment by crystalJinamd** [comment] 2018-06-04 10:04
@libcg Yes, DOOMx64vk.exe will be running if force to set vulkan mode using "r_renderAPI 1" in DOOMConfig.cfg/ DOOMConfig.local. 

Can you try to delete "~/.wine/drive_c/users/root/Saved Games/id Software/DOOM/" then to run the game, if it is still run well, can you help to use "apitrace trace wine64 DOOMx64.vk" to capture trace ?Thanks! BTW, it is also fail to launch DOOM on NV asic. So it maybe app problem.

**Comment by crystalJinamd** [comment] 2018-07-17 06:39
There's a bug already filled for this launch problem: https://bugs.winehq.org/show_bug.cgi?id=44856. And latest wine3.11 works now.

**Comment by libcg** [comment] 2018-08-21 04:16
DOOM now starts as of xgl@d7dd652 and wine-staging 3.13.1, but I'm getting a crash just after the Bethesda logo.

**Comment by crystalJinamd** [comment] 2018-09-04 04:57
The issue is fixed internally.

**Comment by jinjianrong** [comment] 2018-09-04 05:07
The issue should have been fixed in latest code. Please try it

**Closed by jinjianrong** 2018-09-04 05:07 UTC
Labels: assigned, fixed
